spring:
  application:
    name: FileAPI
  datasource:
    url: ${FILE_API_DB_URL}
    username: ${FILE_API_DB_USERNAME}
    password: ${FILE_API_DB_PASSWORD}
  jpa:
    generate-ddl: true

aws:
  endpoint-url: ${AWS_ENDPOINT_URL}
  bucket-name: ${AWS_BUCKET_NAME}
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_ACCESS_KEY}
  local-storage-path: ${LOCAL_STORAGE_PATH}

camel:
  songFileToEnricherServiceQueue: ${SONG_FILE_ENRICHER_SERVICE_QUEUE}
#  aws2-sqs://songFileToEnricherService?amazonSQSClient=#sqsClient expected configuration
  songFileDeletionToSongAPIQueue: ${SONG_FILE_SONG_API_DELETION_QUEUE}
#  aws2-sqs://songFileDeletionToSongAPI?amazonSQSClient=#sqsClient expected configuration

rsa:
  public-key: ${PUB_KEY}

auth-api:
  get-user-endpoint: ${GET_USER_URL}

spring.servlet.multipart:
  max-file-size: 15MB
  max-request-size: 15MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_REGISTRY_DEFAULT_ZONE}

server:
  servlet:
    context-path: /api
